### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [GianlucaGuarini/icaro#16]
Hi, what is the current status of this project? Is it still actively maintained?

**Comment by GianlucaGuarini** [comment]
This is an issue tracker and it works in this way:

1. Don't open any issue
2. Have you found a bug? 
  - `yes`: please reproduce it
  - `no`: go to 1
3. Have you suggestions or feature requests?
  - `yes`: please try to describe it in order to know if the maintainer will implement it
  - `no`: go to 1
4. Have you patched the project improving it?
  - `yes`: please create a PR
  - `no`: go to 1

Please try again trying to be more constructive adding concrete info to the issue.
✌️

**Comment by DanielRuf** [comment]
Sorry but your reply is not very nice.

> This is an issue tracker and it works in this way:

> 1. Don't open any issue

> go to 1

Very stupid answer tbh.
